### ISSUE TITLE
How to analyze the specific crash

### ISSUE THREAD

**Issue by Cr1t-GYM** [RiS3-Lab/DICE-DMA-Emulation#4]
Thanks for your help and I have run my binary successfully. However, I didn't know the reason why this crash came into being. I mean I have tried to use gdb to analyze the crash but the problem printed by run_fw.py was too vague to analyze. There are two problems listed following.
1. Uncategorized register 0x40020084 is accessed!
2. [80026fc, 8002738] illegal read at 0x20013787.

For the first problem, I have noted comment in memory.c tells it only happens in fuzzing, which makes me confused. For the second one, without analyzing the register information I guess it is a kind of problem related to segmentation fault or array out of bounds. Is that correct?

Thanks for your prompt attention.

Sincerely,
Cr1t

**Comment by alejoseb** [comment]
When are you getting  these messages?  are you using any specific input file?
Message 1 normally occurs when your json file has no model for the address 0x40020084. If this is a valid peripheral address it means that the input file is making the firmware to access new peripherals, or P2IM was not able to extract correctly the model beforehand. You may check other errors during model extraction and see if you have a complete model. 

Message 1 normally appears during fuzzing, and it will automatically trigger a new model extraction round with the input file until all interfaces are modeled.  So I guess you are running the firmware with a specific input, bur not extracting the model.

For message 2 it is definitively an out of bounds operation detected by QEMU-P2IM, so it means that you eventually  triggered a a real bug.

**Comment by Cr1t-GYM** [comment]
I got these message 1 when I tried to fuzz stm32f103xe. My input file was full of some random number which was created by myself.

I have noted that there weren't any errors like traceback during model extraction. After I saw a crash in afl-fuzz GUI, I stopped it, tried to debug this crash via using arm-gdb and got message 1. Here are some traces related to address 0x40020084 in rounds of on-demand model instantiation.
```
(0x40020084, 3, w, 6) in BBL (0x8006484, 0x80064b2) [DMA_SetConfig]  // 1.0/0.input.data.1/reg_acc-depth:1,stage:1.0
[8006484, 80064b2] 286-th(total 286-th)   pm_w *0x40020084 = 0x6, remains DR  // 1.0/0.input.data.15/dma_trace
```
Therefore, I believe P2IM have finished extraction status successfully but incorrectly as there are model outputs related to address 0x40020084. I have used afl-fuzz before and I noted that the color of "cycles done" in afl-fuzz GUI is associated with the fuzzing status. As the fuzzing status goes on, the color would turn to red, yellow, blue and finally green. However, that crash, which resulted in message 1, didn't lead to the color change or new edges immediately. From my point of view, maybe that crash is a kind of false positive.

**Comment by alejoseb** [comment]
did you provide the json file as an input to QEMU when debugging with gdb? 
if you did not provide the correct model file then that is the reason for the  message related to 0x40020084.

Besides, the color of AFL GUI shows the number of cycles done (you need to read AFL documentation for more details). Ideally, it takes many hours or days to complete just a single cycle so you should not see color changes right away. If you observe a color change very early that means that something is wrong, probably the coverage is too shallow and P2IM is not able to model correctly your firmware. 

Also yes, false positives might appear that is expected in any fuzzing tool.

You should check the documentation of P2IM, it includes some scripts to verify coverage, that might give you some hints about the functions of your firmware that are covered and if your firmware is crashing in a particular point.

**Comment by Cr1t-GYM** [comment]
I have checked run_fw.py and it gives the correct path to peripheral_model.json. Thanks for your patience to explain details about AFL. 

I'll try to utilize the script to verify fuzzing coverage right away. By the way, when I debugged the crash, I found that the seed did touch my core codes.

**Comment by Cr1t-GYM** [comment]
Coverage reports.
```
Function coverage: 101/171 = 59.06%

{'0x80001e4': ('__do_global_dtors_aux', False),
 '0x8000208': ('frame_dummy', True),
 '0x8000224': ('__aeabi_drsub', False),
 '0x800022c': ('__aeabi_dsub', False),
 '0x8000230': ('__adddf3', False),
 '0x80004a8': ('__aeabi_ui2d', False),
 '0x80004c8': ('__aeabi_i2d', False),
 '0x80004ec': ('__aeabi_f2d', False),
 '0x8000530': ('__aeabi_ul2d', False),
 '0x8000540': ('__aeabi_l2d', False),
 '0x800059c': ('__gedf2', False),
 '0x80005a4': ('__ledf2', False),
 '0x80005ac': ('__cmpdf2', False),
 '0x8000628': ('__aeabi_cdrcmple', False),
 '0x8000638': ('__aeabi_cdcmpeq', False),
 '0x8000648': ('__aeabi_dcmpeq', False),
 '0x800065c': ('__aeabi_dcmplt', False),
 '0x8000670': ('__aeabi_dcmple', False),
 '0x8000684': ('__aeabi_dcmpge', False),
 '0x8000698': ('__aeabi_dcmpgt', False),
 '0x80006ac': ('__aeabi_d2uiz', False),
 '0x80006ec': ('Reset_Handler', True),
 '0x80006f0': ('CopyDataInit', True),
 '0x80006f8': ('LoopCopyDataInit', True),
 '0x8000706': ('FillZerobss', True),
 '0x800070c': ('LoopFillZerobss', True),
 '0x8000734': ('ADC1_2_IRQHandler', False),
 '0x8000736': ('APP_Init', True),
 '0x800076c': ('main', True),
 '0x80007d8': ('SystemClock_Config', True),
 '0x800085a': ('Error_Handler', True),
 '0x8000868': ('MX_GPIO_Init', True),
 '0x8000974': ('MX_DMA_Init', True),
 '0x8000a00': ('MX_USART1_UART_Init', True),
 '0x8000a54': ('MX_USART2_UART_Init', True),
 '0x8000aac': ('MX_USART3_UART_Init', True),
 '0x8000b00': ('HAL_UART_MspInit', True),
 '0x8000ef4': ('Usart3Receive_IDLE', False),
 '0x8000fd0': ('Usart1Receive_IDLE', False),
 '0x800108c': ('Usart2Receive_IDLE', False),
 '0x8001148': ('Usart3SendData_DMA', False),
 '0x8001194': ('Usart1SendData_DMA', False),
 '0x80011e0': ('Usart2SendData_DMA', True),
 '0x800122c': ('NMI_Handler', False),
 '0x8001238': ('HardFault_Handler', False),
 '0x800123e': ('MemManage_Handler', False),
 '0x8001244': ('BusFault_Handler', False),
 '0x800124a': ('UsageFault_Handler', False),
 '0x8001250': ('SVC_Handler', False),
 '0x800125c': ('DebugMon_Handler', False),
 '0x8001268': ('PendSV_Handler', False),
 '0x8001274': ('SysTick_Handler', True),
 '0x8001288': ('DMA1_Channel2_IRQHandler', True),
 '0x800129c': ('DMA1_Channel3_IRQHandler', True),
 '0x80012b0': ('DMA1_Channel4_IRQHandler', True),
 '0x80012c4': ('DMA1_Channel5_IRQHandler', True),
 '0x80012d8': ('DMA1_Channel6_IRQHandler', True),
 '0x80012ec': ('DMA1_Channel7_IRQHandler', True),
 '0x8001300': ('I2C1_EV_IRQHandler', False),
 '0x800130c': ('I2C1_ER_IRQHandler', False),
 '0x8001318': ('USART1_IRQHandler', True),
 '0x8001340': ('USART2_IRQHandler', True),
 '0x8001368': ('USART3_IRQHandler', True),
 '0x8001390': ('HAL_MspInit', True),
 '0x80013f4': ('crc_ccitt', False),
 '0x8001448': ('TSK_Thread_Timer_Func', True),
 '0x8001640': ('TSK_Thread_1min_Funcs', True),
 '0x8001660': ('TSK_Thread_500ms_Funcs', True),
 '0x8001724': ('TSK_Thread_100ms_Funcs', True),
 '0x8001840': ('TSK_Thread_10ms_Funcs', True),
 '0x80019d4': ('TSK_Thread_1ms_Funcs', True),
 '0x8001a48': ('Pulse_2_Manange_Init', True),
 '0x8001ac4': ('Pulse_3_Manange_Init', True),
 '0x8001b40': ('PowerEnable_1_Manange_Init', True),
 '0x8001bc4': ('PowerEnable_2_Manange_Init', True),
 '0x8001c24': ('PowerEnable_3_Manange_Init', True),
 '0x8001c8c': ('Systme_Logic_Init', True),
 '0x8001cc4': ('System_Logic', True),
 '0x8001ff0': ('V1_Output_Ctrl', True),
 '0x8002188': ('V2_Output_Ctrl', True),
 '0x8002484': ('V3_Output_Ctrl', True),
 '0x8002780': ('LED_Drive_Ctrl', True),
 '0x80028b8': ('LED_Ctrl_Init', True),
 '0x80028f4': ('USART_422_Init', True),
 '0x8002960': ('USART_422_Receive', True),
 '0x8002f34': ('USART_422_CMD_Respons', True),
 '0x8002f5c': ('USART_422_ReportData_Package', False),
 '0x80030ac': ('Report_Data_Package', False),
 '0x80032b4': ('Get_2s_Frame', True),
 '0x8003330': ('Sum_Checkout', True),
 '0x8003370': ('USART_Current_Init', True),
 '0x80033d0': ('USART_Current_Receive', True),
 '0x800352c': ('USART_Current_SendData_Package', True),
 '0x800372c': ('OutputMonitor_Init', True),
 '0x8003ab4': ('OutputCurrent_Monitor', False),
 '0x8003bf4': ('Hiccp_Manage', True),
 '0x8003c4c': ('OutputVoltage_Monitor', True),
 '0x8003d36': ('OutputVoltage_Set', False),
 '0x8003de4': ('Output3_Compensation', False),
 '0x8003e88': ('USART_U35_Init', True),
 '0x8003edc': ('USART_U35_Receive', True),
 '0x8003f8c': ('USART_U35_SendData_Package', True),
 '0x8004190': ('Monitor_Temperature_Calculate', True),
 '0x8004294': ('Temperature_Manage', False),
 '0x800430c': ('Max_Temperature_Canculate', False),
 '0x8004354': ('aflCall', True),
 '0x800435c': ('startForkserver', True),
 '0x800438c': ('HAL_UART_Init', True),
 '0x8004426': ('HAL_MultiProcessor_Init', True),
 '0x8004508': ('HAL_UART_Transmit_DMA', True),
 '0x80045e0': ('HAL_UART_Receive_DMA', True),
 '0x80046e0': ('HAL_UART_DMAStop', False),
 '0x8004798': ('HAL_UART_IRQHandler', True),
 '0x800498c': ('HAL_UART_TxCpltCallback', False),
 '0x800499e': ('HAL_UART_TxHalfCpltCallback', False),
 '0x80049b0': ('HAL_UART_RxCpltCallback', False),
 '0x80049c2': ('HAL_UART_RxHalfCpltCallback', False),
 '0x80049d4': ('HAL_UART_ErrorCallback', False),
 '0x80049e6': ('UART_DMATransmitCplt', False),
 '0x8004a38': ('UART_DMATxHalfCplt', False),
 '0x8004a54': ('UART_DMAReceiveCplt', False),
 '0x8004abc': ('UART_DMARxHalfCplt', False),
 '0x8004ad8': ('UART_DMAError', False),
 '0x8004b6c': ('UART_EndTxTransfer', False),
 '0x8004b96': ('UART_EndRxTransfer', False),
 '0x8004bd0': ('UART_DMAAbortOnError', False),
 '0x8004bf8': ('UART_Transmit_IT', False),
 '0x8004ca2': ('UART_EndTransmit_IT', False),
 '0x8004cd2': ('UART_Receive_IT', False),
 '0x8004dd4': ('UART_SetConfig', True),
 '0x8004f88': ('HAL_Init', True),
 '0x8004fb4': ('HAL_InitTick', True),
 '0x8005014': ('HAL_IncTick', True),
 '0x8005038': ('HAL_GetTick', True),
 '0x800504c': ('HAL_RCC_OscConfig', True),
 '0x800554c': ('HAL_RCC_ClockConfig', True),
 '0x8005720': ('HAL_RCC_GetSysClockFreq', False),
 '0x80057e4': ('HAL_RCC_GetHCLKFreq', True),
 '0x80057f8': ('HAL_RCC_GetPCLK1Freq', True),
 '0x8005820': ('HAL_RCC_GetPCLK2Freq', True),
 '0x8005848': ('RCC_Delay', False),
 '0x8005884': ('HAL_GPIO_Init', True),
 '0x8005bac': ('HAL_GPIO_WritePin', True),
 '0x8005bdc': ('HAL_DMA_Init', True),
 '0x8005cc8': ('HAL_DMA_Start_IT', True),
 '0x8005d86': ('HAL_DMA_Abort', False),
 '0x8005dfc': ('HAL_DMA_Abort_IT', False),
 '0x800600c': ('HAL_DMA_IRQHandler', True),
 '0x8006484': ('DMA_SetConfig', True),
 '0x80064e0': ('NVIC_SetPriorityGrouping', True),
 '0x8006528': ('NVIC_GetPriorityGrouping', True),
 '0x8006544': ('NVIC_EnableIRQ', True),
 '0x8006574': ('NVIC_SetPriority', True),
 '0x80065c8': ('NVIC_EncodePriority', True),
 '0x800662c': ('SysTick_Config', True),
 '0x8006670': ('HAL_NVIC_SetPriorityGrouping', True),
 '0x8006686': ('HAL_NVIC_SetPriority', True),
 '0x80066be': ('HAL_NVIC_EnableIRQ', True),
 '0x80066da': ('HAL_SYSTICK_Config', True),
 '0x80066f2': ('HAL_SYSTICK_IRQHandler', True),
 '0x80066fe': ('HAL_SYSTICK_Callback', True),
 '0x800670c': ('SystemInit', True),
 '0x8006774': ('__libc_init_array', True),
 '0x80067bc': ('memset', True),
 '0x800685c': ('register_fini', True),
 '0x8006870': ('atexit', False),
 '0x800687c': ('__libc_fini_array', False),
 '0x80068a8': ('__retarget_lock_acquire_recursive', False),
 '0x80068ac': ('__retarget_lock_release_recursive', False),
 '0x80068b0': ('__register_exitproc', False),
 '0x800693c': ('_init', True)}

```

**Comment by Cr1t-GYM** [comment]
The function coverage is 59.06%.

One more thing that bothers me is about how to find the bug in codes associated with specific crash. For instance, listing 1 mentioned on page 14 of [DICE's paper](https://www.longlu.org/publication/dice/dice.pdf) shows me several lines of codes which might lead to crash. How can I debug the sources with crash input to find these codes? I already tried the ModBus fuzzing and got some crashes. Nevertheless, most of them resulted from function "prvPortStartFirstTask", which is from the source of FreeRTOS. I don't think it was the inline code in function "prvPortStartFirstTask" that led to crash. What is your opinion?

Have a lovely day.

Sincerely,
Cr1t

**Comment by alejoseb** [comment]
Crash triage is one of the most tedious task, that is expected for any fuzzing tool. Crash triage is an orthogonal problem not solved by our tools.

For Modbus we used a slightly modified version of the firmware with red-zones to catch  out-of-bounds operations, check details in page 12 of the DICE paper. The repository includes also the binary and source code for this modified version. If you use this version you need to provide the address and size of the red-zones (we also provide them in the repository). When you fuzz with this particular version  you will get several crashes. To quickly identify real crashes related to bugs, we run (without gdb) the firmware with the red-zone file, the corresponding model and the AFL generated input files for each of the crashes. For a potential real bug, QEMU should finish execution with a message similar to this:
"[%x, %x] illegal read/write at canary 0x%x\n"   where [%x, %x] are the start and finish addresses of the "basic block" where the illegal access happened---but not the root cause.  

Using this information you have to debug the firmware  using GDB and trace-back the whole firmware execution in QEMU to identify the root cause of the illegal operation.

**Comment by findo** [comment]
@alejoseb 
1. In your paper, you write 
> We inserted red-zones before and after buffers at compile time

Why does **only** Modbus have red-zones compiled version `Modbus-Redzones.elf` ? How to compile modbus with red-zones? 
2.  
> Using this information you have to debug the firmware using GDB and trace-back the whole firmware execution in QEMU to identify the root cause of the illegal operation.

I found it is extremely difficult to locate the root cause (like **Listing 1** in page 14). To debug the firmware, I first add a breakpoint at `main` function, then run `continue` to reach the breakpoint. After that, run `next` to execute the firmware. I try to debug with three crashes, QEMU always immediately exits after the following function is executed:
![image](https://user-images.githubusercontent.com/11796555/101568731-1a4ae080-3a0e-11eb-97a8-fddceeddd1ff.png)
I haven't found any crash that is caused by core code of firmware like **Listing 1**. Are those crashes all false positive ? Can you provide one crash input that is crashed by Bug ID 1, 2, or 3 for Modbus ?

Thanks

**Comment by alejoseb** [comment]
> Why does **only** Modbus have red-zones compiled version `Modbus-Redzones.elf` ? 

We tested all firmware with and without red-zones, however we only found bugs in Modbus using this method, that is the reason we only provide a Modbus version with red-zones. Red-zones are just one of the methods that you can implement to improve bug catching, but that is beyond the scope of P2IM and DICE. You can take a look to this work that further discusses this issue: http://s3.eurecom.fr/docs/ndss18_muench.pdf. 

>How to compile modbus with red-zones?

Check the source code of Modbus of our repository, it has some arrays called "canaries" surrounding the Modbus TX and RX buffers. You have to compile the source code and check that the compiler actually included the "canaries" surrounding the TX and RX buffers. Then you have to get the addresses of the "canaries" and create a file  similar to this https://github.com/RiS3-Lab/DICE-DMA-Emulation/blob/master/DICE-Evaluation/ARM/Fuzzing/Redzones/Modbus-Redzones.txt
To get this information you can use a debugger, Ghidra or any other reverse engineering tool. 

Note: "canaries" are technically red-zones, no stack canaries, it is just a legacy of our testing.

> 2. 

I suppose you are debugging some FreeRTOS code because of the listing, I cannot help you just watching the listing that you provide. Eventually, you need to debug step by step until you isolate the issue. Probably, they are false positives. I have no more comments about it.

I will upload some inputs for the real crashes for Modbus. However, to reproduce the crash you also need the same model, firmware, and QEMU. Therefore, it is possible you do not observe the same result. Also I will not upload that information because is particular for my environment.
My recommendation is to use directly the firmware, configuration file, red-zones and QEMU that we provided to reproduce our experiment. The whole environment and experiment are validated, you will get real crashes.

**Comment by findo** [comment]
@alejoseb 
Thanks for your replay!!! Really appreciate it !!!!!
I try to reproduce the crash found for GPSReceiver. The firmware crashes at line 379 as follows 
![image](https://user-images.githubusercontent.com/11796555/101897068-f097e200-3be4-11eb-90d4-dff7054e9dad.png)
The value of `*d` is 0. I wonder why it crashes at `else if (*d == '*')`. The gdb window is:
![image](https://user-images.githubusercontent.com/11796555/101897446-85024480-3be5-11eb-9da8-b69c07484702.png)
QEMU issues `DMA buffer wrap around! finishing fuzzing session`. What is meaning of `DMA buffer wrap around` ?
![image](https://user-images.githubusercontent.com/11796555/101898062-78322080-3be6-11eb-9d92-c4701710ec42.png)

The attachment contains the crash input, `run_fw.py`, etc.
[GPSReceiver.zip](https://github.com/RiS3-Lab/DICE-DMA-Emulation/files/5678849/GPSReceiver.zip)

**Comment by alejoseb** [comment]
DMA buffer wrap around means that you run-out of input data from fuzzer, that is a normal condition to finish a fuzzing run, it is not a crash by itself, you can safely ignore all of them.
