### ISSUE TITLE
L1521 or F105

### ISSUE THREAD

**Issue by valuta1995** [RiS3-Lab/DICE-DMA-Emulation#5]
Hi,
For my thesis I am working with DMA on the Nucleo L152 (re) platform. When I wanted to try some of the firmware I had compiled with DICE, I got some nondescript issues.
`ret_val == 0xFF, re-run it!`
After three times, the re-run attempt stop and a python trace is produced:
- me.py:1158 <module>
- me.py:358 stage1()
- me.py:192 qemu_run()

From what I can see the L1521 maps to the F105 platform inside of DICE. Is this an unfortunate name change or is the L152 platform executable when F105 is selected on qemu's side of things?

Screenshot included:
https://cdn.discordapp.com/attachments/783312794367557682/814879611128381454/unknown.png

**Comment by alejoseb** [comment]
Hi,
L152 was not part of our test and development. You should check the documentation of P2IM (https://github.com/RiS3-Lab/p2im) to extend QEMU to support your board, mapping to a similar MCU might not work. You should first verify that QEMU+P2IM is able to run your firmware and extract peripheral models, then you can  verify the DMA support with DICE. Be aware of P2IM limitations since some complex firmware might halt very early and will not cover much code nor get the models.
